PLANNING_HORIZON_DAYS = 7
SAFETY_STOCK_DAYS = 3
DEMAND_CONFIDENCE_FACTOR = 0.90

MAX_TRANSFER_ROUTES_PER_PRODUCT = 20
MIN_UNIT_NET_GAIN = 1

DEFAULT_COST_PER_UNIT_SAME_CITY = 1
DEFAULT_COST_PER_UNIT_DIFF_CITY = 2
DEFAULT_FIXED_COST_SAME_CITY = 5
DEFAULT_FIXED_COST_DIFF_CITY = 10